### ISSUE TITLE
Override MAVEN_CENTRAL In Build Wrapper

### ISSUE THREAD

**Issue by milindbangar79** [rife2/bld#2]
Hi,

How can I override MAVEN_CENTRAL to our internal Maven Repo?

This one is blocked --> https://repo1.maven.org/maven2/

Thanks
Milind

**Comment by gbevin** [comment]
Hi, you can provide any repository URL in the wrapper and in bld itself, just put the URL instead of the alias.
https://github.com/rife2/bld/wiki/Extensions#extension-repositories
