### ISSUE TITLE
create command should also create .gitignore file

### ISSUE THREAD

**Issue by paul-hammant** [rife2/bld#21]
That said, it could be there's nothing to be auto added to a `.gitignore` file.

I would think that not all of bld, compile,  provided, runtime, standalone, test, from `iib/` need to be checked into source control. Some of them can be hot re-aquired by the person cloning and running their first **bld** build

`

**Comment by gbevin** [comment]
There is a .gitignore file added, does it not for you?
<img width="866" alt="Screenshot 2024-02-24 at 12 04 02" src="https://github.com/rife2/bld/assets/701148/57ca9550-3759-43c5-81d0-35d2e2f4ea67">

**Comment by paul-hammant** [comment]
Indeed, that was user error
