### ISSUE TITLE
Create cache / offline support e.g. with .m2

### ISSUE THREAD

**Issue by YunaBraska** [rife2/bld#24]
I love this build system.
Would be nice to have the possibilities to use the `.m2` or `.gradle` or a new `.blb` global folder

**Comment by gbevin** [comment]
Hi @YunaBraska,

`bld` purposefully doesn't create a global artifact cache where it puts dependencies jars. However, like Erik says you can use the local `.m2` Maven directory as a local repository. Having a mutable local cache that is shared across all project creates very difficult problems and it's one of the causes of Gradle's and Maven's complexity. Multiple project accessing the same global cache and modifying it at the same time, takes careful planning and coordination, including having a background daemon that can get stale, need restarting, ...

`bld` takes the approach that your dependencies are not something that you update all the time, and that this is a task you usually purposefully do and should be fully engaged with (you're replacing fundamental pieces of your software with new ones coming from anonymous places on the internet). You should even be able to not use any automated means and manually use jars as dependencies without it being a hassle (you can just drop them in the right directory).

**Comment by YunaBraska** [comment]
Sounds like a bit too much manual work like `just drop them in the right directory`. I work many times offline ;)
