### ISSUE TITLE
JEP458 opportunity?

### ISSUE THREAD

**Issue by hrstoyanov** [rife2/bld#27]
This [JEP458](https://openjdk.org/jeps/458) delivered in java 22 may allow for running the BLD project files without needing to compile them, avoiding the "chickedn-and-egg" problem mentioned in the docs. Just fyi, since it is Java 22...

Is there a way to run in BLD in "online mode", watching the file system and launching builds as needed?, maybe caching things in the process?

**Comment by gbevin** [comment]
Thanks, we'll take a look at JEP458.

There's no online mode for bld at this time.

**Comment by ethauvin** [comment]
Just to add closure to this issue…

Our initial testing with JEP458 yielded very little benefits at this point. Some of the design decisions we made to avoid unintended side effects are just not meshing well.
