### ISSUE TITLE
Dependency with unusual version number cannot be specified

### ISSUE THREAD

**Issue by branscha** [rife2/bld#28]
For example javax-help with this maven dependency (notice "05" in version number) cannot be specified in BLD; the version type assumes integers. When providing a string "2.0.05" it will be converted to 2.0.5 and the dependency will not be resolved.

```
<dependency>
    <groupId>javax.help</groupId>
    <artifactId>javahelp</artifactId>
    <version>2.0.05</version>
</dependency>
```

This will not work:

```
dependency("javax.help", "javahelp", "2.0.05")
dependency("javax.help", "javahelp", version(2, 0, 05))
```

You will get

`Couldn't find artifact for dependency 'javax.help:javahelp:2.0.5' at https://repo1.maven.org/maven2/javax/help/javahelp/2.0.5/javahelp-2.0.5.pom`

**Comment by gbevin** [comment]
Hi, these dependencies rely on the string qualifier being interpreted for the last part. We can likely improve the string parser. In the meantime, this dependency can be specified like this:

```
dependency("javax.help", "javahelp", new VersionNumber(2, 0, null, "05", "."))
```

**Comment by gbevin** [comment]
Pushed a fix for this, the parser will now detect this. I'll try to release the next bld version soon.
