### ISSUE TITLE
Unreliable evaluation of variable $USER_HOME$ for IntelliJ IDEA when using Windows Subsystem for Linux

### ISSUE THREAD

**Issue by kilathaar** [rife2/bld#3]
The generated configuration file *bld.xml* for IntelliJ IDEA uses the variable `$USER_HOME$` to declare the path to bld (`<root url="jar://$USER_HOME$/.bld/dist/bld-1.7.0.jar!/" />`) which does not evaluate to correct path when bld is installed via Windows Subsystem for Linux and IntelliJ IDEA is installed under Windows.

Given the user `bob` and bld is installed under WSL.

Path to bld: `\\wsl$\Ubuntu\home\bob\.bld\dist\bld-1.7.0.jar`

IntelliJ IDEA will however evaluate `$USER_HOME$/.bld/dist/bld-1.7.0.jar` to `C:\Users\bob\.bld\dist\bld-1.7.0.jar` and thus won't find the path to `rife.bld.Project`.

It "only" seems to impact the IntelliJ IDEA editor when browsing the build class, the run configuration for IDEA still works fine.

**Comment by gbevin** [comment]
Since IDEA is replacing that variable, this seems like an IDEA bug, could you report it to them?
