### ISSUE TITLE
Stop treating version like numbers

### ISSUE THREAD

**Issue by tribals** [rife2/bld#30]
Hello!

Just got a bug that prevents installation of a library I'm willing to try. Here is snippet causing a problem:

```java
public class FooBuild extends BaseProject {
    final static Repository REPORTMILL = new Repository("https://reportmill.com/maven");

    public FooBuild() {
        pkg = "foo";
        name = "bar";
        mainClass = "bar.foo.Main";
        version = version(0, 0, 1);

        repositories = List.of(MAVEN_CENTRAL, REPORTMILL);

        scope(compile).include(
            dependency("com.reportmill", "snapkit", version("2024.02"))  // <-- HERE
        );
    }
}
```

Whenever I'm trying to `./bld download`, I got the error:

```
Couldn't find artifact for dependency 'com.reportmill:snapkit:2024.2' at https://reportmill.com/maven/com/reportmill/snapkit/2024.2/snapkit-2024.2.pom, https://repo1.maven.org/maven2/com/reportmill/snapkit/2024.2/snapkit-2024.2.pom
```
Here is some valid URL for that repo: https://reportmill.com/maven/com/reportmill/snapkit/2024.02/

Notice the difference:

```diff
-2024.02
+2024.2
```

That's not how it is supposed to be...

This is because of that:

```java
// rife.bld.dependencies.VersionNumber
    public static VersionNumber parse(String version) {
        <...>
        var major_integer = (major != null ? Integer.parseInt(major) : null);
        var minor_integer = (minor != null ? Integer.parseInt(minor) : null);
        var revision_integer = (revision != null ? Integer.parseInt(revision) : null);
        <...>
    }
```

This is wrong. You shouldn't do that. Sometimes people are getting very creative about versioning. But even when there is some kind of "standard" in place, like "semantic versioning" - versions are still not numbers.

**Comment by gbevin** [comment]
I'm looking now at how to improve the string parser to automatically use the qualifier for this.

**Comment by tribals** [comment]
Will try proposed solution and report on success later.

> I took a look at this, semantic versioning does specify that X.Y.X are non-negative integers, thus numbers.

Standards are good, but you can't force everyone to follow them, and sometimes people will not - but you still need to deal with it somehow.

If there is some way to achieve this - I'm happy!

**Comment by gbevin** [comment]
Pushed a fix for this, the parser will now detect this. I'll try to release the next bld version soon.

**Comment by tribals** [comment]
We apparently need "fire" reaction on github!

^_^
