### ISSUE TITLE
[1.9.1] BLD issue with Java 22 and --enable preview compile option

### ISSUE THREAD

**Issue by hrstoyanov** [rife2/bld#33]
BLD compile the build class befoe even consulting the compileOptions() somehow, missing the preview flag and and failg, even for things like "./bld help".

Details here:
https://discord.com/channels/936955360714031144/1098438169936007168/1241591205528338503
https://discord.com/channels/936955360714031144/1098438169936007168/1241692465942102146

**Comment by gbevin** [comment]
The compile options are for the code that `bld` compiles, not for the build process code itself, there's currently no way to pass options there.

It could be a feature to consider for a future update.

**Comment by gbevin** [comment]
`bed-wrapper.properties` can now take options to configure java and javac :

```
bld.downloadExtensionJavadoc=false
bld.downloadExtensionSources=true
bld.downloadLocation=
bld.extension-antlr=com.uwyn.rife2:bld-antlr4:1.2.8
bld.extension-archive=com.uwyn.rife2:bld-archive:0.4.8
bld.extension-tests=com.uwyn.rife2:bld-tests-badge:1.4.8
bld.javaOptions=--enable-preview
bld.javacOptions=--enable-preview --release 23
bld.repositories=MAVEN_CENTRAL,RIFE2_RELEASES
bld.sourceDirectories=core/src/bld/java
bld.version=1.9.2-SNAPSHOT
```
