### ISSUE TITLE
bld extension for things that generates code (ex. dagger2)

### ISSUE THREAD

**Issue by sombriks** [rife2/bld#35]
how one could create an extension to perform such task? 
i was troubleshooting a dagger2 issue and was using bld for fast investigation but got stuck on that part.

**Comment by ethauvin** [comment]
Not sure an extension would be needed, but I'm not that familiar with Dagger, so bare with me.

Isn't Dagger using an annotation processor? In that case, take a look at:

* https://forum.uwyn.com/post/36

If an extension is needed, we have [many extensions](https://github.com/rife2/bld/wiki/Extensions) that call other tools.

If you can outline what you'd like the extension to do, I'd be happy to help.

**Comment by gbevin** [comment]
Closing since it doesn't seem like this should be a generic extension specifically for code generation.
