### ISSUE TITLE
[1.9.1] Issue with extensions dependencies.

### ISSUE THREAD

**Issue by hrstoyanov** [rife2/bld#36]
Maybe I missed something in the docs, but here is something strange. I expected below extensions config to download 2 jars in **lib/bld** for my build code to use:
```
bld.downloadExtensionJavadoc=false
bld.downloadExtensionSources=true
bld.extensions=peruncs:peruncs-platform:0.0.1, com.uwyn.rife2:bld:1.9.1
bld.repositories=MAVEN_LOCAL,MAVEN_CENTRAL
bld.downloadLocation=
bld.sourceDirectories=
bld.version=1.9.1
```

but I only get **peruncs-platform-0.0.1.jar** , the other one did not download?

**Comment by gbevin** [comment]
bld filters itself out from the extensions since it already is available in the class path, have you tried with another artifact as the extensions to download. It works fine in my local testing

**Comment by gbevin** [comment]
bld is installed in `<yourhome>/.bld/dist/bld-1.9.1.jar`, it is already defined in the `.idea/libraries/bld.xml` library and that is also what is automatically updated when you upgrade bld. It definitely should not be an extension.
