### ISSUE TITLE
Extensions throwing exceptions do not stop execution

### ISSUE THREAD

**Issue by ethauvin** [rife2/bld#41]
I haven't had a chance to track it down, but this is how I reproduced it with this (bld) project.

I modified the build file's `antlr4Operation` to point to an invalid location, which would make it fail, then issued:

```console
./bld all version
```

The antlr extension operation [threw an exception](https://github.com/rife2/bld-antlr4/blob/main/src/main/java/rife/bld/extension/Antlr4Operation.java#L53), but the version was still displayed.

To confirm that non-extension operation do stop the execution. I made the `rife.bld.TestWebProject` test fail, then issued:

```console
./bld test --select-class=rife.bld.TestWebProject version
```

The test failed, and the version was never displayed.

Of course, I observed the same behavior with one of my extension, but I wanted to confirm it wasn't just my code.

As i was writing this, I just thought of trying:

```java
@Override
public void compile() throws Exception {
    throw new Exception();
}
```

And it does not stop execution either.

**Comment by gbevin** [comment]
To stop the execution, the command has to explicitly throw the `ExitStatusException`, otherwise `bld` indeed only prints an error message but continues the execution.

**Comment by ethauvin** [comment]
@gbevin Thanks. That makes sense now. I've got to update a few extensions.
