### ISSUE TITLE
using bld to publish on github maven registry

### ISSUE THREAD

**Issue by sombriks** [rife2/bld#44]
is it possible to use bld to publish on github package registy?
i've found wiki instructions for maven sonatype, i assumed that it should work just fine with github package registry.

here's the sample project:
https://github.com/sombriks/no-rollback-from-here/blob/main/no-rollback-java/src/bld/java/norollback/NoRollbackBuild.java#L46

am i missing something?

any guidance is welcome.

**Comment by gbevin** [comment]
If it follows the Maven publication flow and API, it should just work. I'm using it with Reposilite here https://repo.rife2.com and it just works. You might have to activate Maven package support in GitHub though.

**Comment by gbevin** [comment]
So yeah, this just works:
https://github.com/orgs/rife2/packages?repo_name=bld

**Comment by sombriks** [comment]
> So yeah, this just works: https://github.com/orgs/rife2/packages?repo_name=bld

A quick heads-up, it works like a charm, it was my token. it was expired 🤡 .

publish command on github repositories will work with as little settings as this:

```java
publishOperation()
                .repository(new Repository(
                        "https://maven.pkg.github.com/sombriks/no-rollback-from-here/"
                ).withCredentials(
                        System.getenv("GITHUB_ACTOR"), 
                        System.getenv("GITHUB_TOKEN")
                ));
```

and to consume the package the repo configuration is pretty much the same:

```java
repositories = List.of(MAVEN_CENTRAL, RIFE2_RELEASES,
                new Repository("https://maven.pkg.github.com/sombriks/*",
                        System.getenv("GITHUB_ACTOR"),
                        System.getenv("GITHUB_TOKEN")
                )
        );
```

according to github the "*" allows to consume all packages from the same owner, but i had no luck with ditch the authentication. yet.

but that's not a bld problem, bld is doing perfectly its job!

**Comment by gbevin** [comment]
Cool, thanks for confirming!
