### ISSUE TITLE
NetBeans support

### ISSUE THREAD

**Issue by maxbrito500** [rife2/bld#53]
Hello Geert and others,

IntelliiJ is all the rage and I use it for Android, but Netbeans is just plain comfy to build code for hours and relax.

How would we go about adding bld there instead of ant or maven? I mean, it is easy for me to run a script but we have big buttons on the IDE to compile things. Maybe possible to request integration with NetBeans too?

Many thanks!

**Comment by gbevin** [comment]
Hi!

Since nobody on the bld team actually uses Netbeans, we have very little incentive to add support for it, nor to research how to do it. I'm sorry, but at this time this is a very low priority for us.

Take care,

Geert

**Comment by maxbrito500** [comment]
No worries, thank you for the quick reply.
